### PR TITLE
Improved Java Examples 

### PR DESCRIPTION
**Pull request by michaelmaxyz**

### CODE REVIEW

**Comment by tspence** [comment]
Looks positive so far.  Is this mostly refactoring or are there any critical changes I should look at?

**Comment by michaelmaxyz** [comment]
mostly just refactoring, rewriting the example programs so they actually look like something a real user would write (not everything in main).

**Comment by tspence** [comment]
Nice!  Are you ready for me to merge?

**Comment by michaelmaxyz** [comment]
Yep!

**Pull request merged**
